<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>SYSLIB0011;CS0114;CS0108</NoWarn>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ArcLegacy</AssemblyName>
    <RootNamespace>GameRes.Legacy</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../GameRes/GameRes.csproj" />
    <ProjectReference Include="../ArcFormats/ArcFormats.csproj" />
  </ItemGroup>
</Project>
