<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>GARbro.Console</AssemblyName>
    <RootNamespace>GARbro</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GameRes/GameRes.csproj" />
  </ItemGroup>
</Project>