<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>SYSLIB0011;CS0114;CS0108</NoWarn>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>GameRes</AssemblyName>
    <RootNamespace>GameRes</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Core" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.9" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
    <PackageReference Include="System.IO.Packaging" Version="10.0.9" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
  </ItemGroup>
</Project>